# This is a basic workflow to help you get started with Actions

name: Selenium Java CI

on: [push]

jobs:
  build:
    runs-on: windows-latest # Using linux machine

    steps:
    - uses: actions/checkout@v2 # Checkout the code
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 # Setup JAVA
      with:
        java-version: 1.8
